
name: Build Artifacts

on:
  push:
    branches: [ sge ]
  # pull_request:
  #   branches: [ master ]
  workflow_dispatch:
  
jobs:
  build_mainnet:
    name: Build Mainnet Artifacts
    runs-on: ubuntu-latest 
    steps:
    - name: Environment
      run:  export NODE_OPTIONS="--max_old_space_size=4096"
      
    - name: Git Checkout Latest
      uses: actions/checkout@v4
      
    - name: Install
      run: yarn install --ignore-engines

    - name: Build
      run: yarn build

    - name: Pack 
      run: | 
        mv dist/ pingpub
        tar -czf pingpub_mainnet.tar.gz ./pingpub/

    - uses: actions/upload-artifact@v4
      with:
        name: pingpub_mainnet.tar.gz
        retention-days: 1

  build_testnet:
    runs-on: ubuntu-latest 
    steps:
    - name: Environment
      run:  export NODE_OPTIONS="--max_old_space_size=4096"
      
    - name: Git Checkout Latest
      uses: actions/checkout@v4

    - name: Update config
      run: |
        cp chains/testnet/sge.json chains/mainnet/sge.json

    - name: Install
      run: yarn install --ignore-engines

    - name: Build
      run: yarn build

    - name: Pack 
      run: | 
        mv dist/ pingpub
        tar -czf pingpub_testnet.tar.gz ./pingpub/
      
    - uses: actions/upload-artifact@v4
      with:
        name: pingpub_testnet.tar.gz
        retention-days: 1

  build_staging:
    runs-on: ubuntu-latest 
    steps:
    - name: Environment
      run:  export NODE_OPTIONS="--max_old_space_size=4096"
      
    - name: Git Checkout Latest
      uses: actions/checkout@v4

    - name: Update config
      run: |
        cp chains/testnet/sge_stage.json chains/mainnet/sge.json
      
    - name: Install
      run: yarn install --ignore-engines

    - name: Build
      run: yarn build

    - name: Pack 
      run: | 
        mv dist/ pingpub
        tar -czf pingpub_staging.tar.gz ./pingpub/

    - uses: actions/upload-artifact@v4
      with:
        name: pingpub_staging.tar.gz 
        retention-days: 1
