
name: Build Artifacts

on:
  push:
    branches: [ sge ]
  # pull_request:
  #   branches: [ master ]
  workflow_dispatch:
  
jobs:
  build_packages:
    outputs:
      MAINPKG: ${{ steps.upload.outputs.EXPLORER }}
      TESTPKG: ${{ steps.upload.outputs.UPDATE }}
      STGPCKG: ${{ steps.upload.outputs.UPDATE }}
    strategy:
      matrix:
        include:
          - env: mainnet
            cfg: "chains/mainnet/sge.json"
          - env: testnet
            cfg: "chains/testnet/sge.json"
          - env: staging 
            cfg: "chains/testnet/sge_stage.json"
    runs-on: ubuntu-latest 
    steps:
    - name: Environment
      run:  export NODE_OPTIONS="--max_old_space_size=4096"
      
    - name: Git Checkout Latest
      uses: actions/checkout@v4

    - name: Update config
      run: |
        if [ ${{ matrix.env }} != "mainnet" ]; then cp ${{ matrix.cfg }} chains/mainnet/sge.json; fi

    - name: Install
      run: yarn install --ignore-engines

    - name: Build
      run: yarn build

    - name: Pack 
      run: | 
        mv dist/ pingpub
        tar -czf pingpub_${{ matrix.env }}.tar.gz ./pingpub/ 

    - uses: actions/upload-artifact@v4
      id: upload
      with:
        name: pingpub_${{ matrix.env }}.tar.gz
        path: pingpub_${{ matrix.env }}.tar.gz
        retention-days: 1

  build_image:
    needs: build_packages
    runs-on: ubuntu-latest

    permissions:
      id-token: write 
      contents: read  

    steps:
      - name: Checkout aws-infra
        uses: actions/checkout@v4
        with: 
          repository: 'saage-tech/aws-infra'
          token:  ${{ secrets.READ_ST }}

      - name: Download 
        uses: actions/download-artifact@v4

      - name: Debug
        run: |
          packer version
          ls -la ./packer/blockexplorer

      - name: Assume role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Packer Init
        run: | 
          cp pingpub_staging.tar.gz/pingpub_staging.tar.gz ./packer/blockexplorer/files/pingpub.tar.gz
          cd packer/blockexplorer
          rm staging.pkr.hcl
          packer init .

      - name: Packer Build 
        working-directory: packer/blockexplorer
        run: |
          packer build -var-file=dev.pkvars.hcl blockexplorer.pkr.hcl