
name: Build Artifacts

on:
  push:
    branches: [ sge ]
  # pull_request:
  #   branches: [ master ]
  workflow_dispatch:
  
jobs:
  build:
    strategy:
      matrix:
        include:
          - matrix.env: mainnet
            matrix.cfg: "chains/mainnet/sge.json"
          - matrix.env: testnet
            matrix.cfg: "chains/testnet/sge.json"
          - matrix.env: staging 
            matrix.cfg: "chains/testnet/sge_stage.json"
    runs-on: ubuntu-latest 
    steps:
    - name: Environment
      run:  export NODE_OPTIONS="--max_old_space_size=4096"
      
    - name: Git Checkout Latest
      uses: actions/checkout@v4

    - name: Update config
      run: |
        cp ${{ matrix.cfg }} chains/mainnet/sge.json

    - name: Install
      run: yarn install --ignore-engines

    - name: Build
      run: yarn build

    - name: Pack 
      run: | 
        mv dist/ pingpub
        tar -cf pingpub_${{ matrix.env }}.tar ./pingpub/ >

    - uses: actions/upload-artifact@v4
      with:
        name: pingpub_${{ matrix.env }}.tar
        path: pingpub_${{ matrix.env }}.tar
        retention-days: 1
